"""Add department yearly budgets

Revision ID: 22450b75200a
Revises: bc57f288a677
Create Date: 2026-04-19 21:56:11.173962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22450b75200a'
down_revision = 'bc57f288a677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_yearly_budgets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('annual_budget_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('annual_budget_amount >= 0', name='ck_department_yearly_budgets_annual_budget_amount_non_negative'),
    sa.CheckConstraint('fiscal_year >= 2000', name='ck_department_yearly_budgets_fiscal_year_min'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'fiscal_year', name='uq_department_yearly_budgets_department_id_fiscal_year')
    )
    with op.batch_alter_table('department_yearly_budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_department_yearly_budgets_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_department_yearly_budgets_fiscal_year'), ['fiscal_year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_yearly_budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_department_yearly_budgets_fiscal_year'))
        batch_op.drop_index(batch_op.f('ix_department_yearly_budgets_department_id'))

    op.drop_table('department_yearly_budgets')
    # ### end Alembic commands ###
