"""make project planned_start_date required

Revision ID: 4f9f41f6e331
Revises: ae9655238863
Create Date: 2026-05-06 00:52:29.468318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f9f41f6e331'
down_revision = 'ae9655238863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('planned_start_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('planned_start_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
