"""add project reports

Revision ID: 70df74dfd081
Revises: f833bd041280
Create Date: 2026-06-20 22:56:23.294410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70df74dfd081'
down_revision = 'f833bd041280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('reporter_id', sa.BigInteger(), nullable=False),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('report_month', sa.Date(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("\n            (\n              report_type = 'monthly'\n              AND report_month IS NOT NULL\n            )\n            OR\n            (\n              report_type = 'completion'\n              AND report_month IS NULL\n            )\n            ", name='ck_project_reports_month_rule'),
    sa.CheckConstraint("report_type IN ('monthly', 'completion')", name='ck_project_reports_report_type_allowed'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_project_reports_project_id_projects'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name='fk_project_reports_reporter_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_reports_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_reports_report_month'), ['report_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_reports_report_type'), ['report_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_reports_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_reports_submitted_at'), ['submitted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_reports_submitted_at'))
        batch_op.drop_index(batch_op.f('ix_project_reports_reporter_id'))
        batch_op.drop_index(batch_op.f('ix_project_reports_report_type'))
        batch_op.drop_index(batch_op.f('ix_project_reports_report_month'))
        batch_op.drop_index(batch_op.f('ix_project_reports_project_id'))

    op.drop_table('project_reports')
    # ### end Alembic commands ###
