"""refactor db models for issue 6

Revision ID: 88311347dd34
Revises: 22450b75200a
Create Date: 2026-04-29 23:31:26.715089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88311347dd34'
down_revision = '22450b75200a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_drafts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('department_id', sa.BigInteger(), nullable=True),
    sa.Column('estimated_person_months', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('estimated_budget_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_drafts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_drafts_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_drafts_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=True))
        batch_op.alter_column('project_id',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)

    op.execute("""
        UPDATE notifications
        SET message = COALESCE(NULLIF(title, ''), '') ||
                      CASE
                        WHEN title IS NOT NULL AND title <> '' AND body IS NOT NULL AND body <> ''
                        THEN '：'
                        ELSE ''
                      END ||
                      COALESCE(NULLIF(body, ''), '')
        WHERE message IS NULL
    """)
    op.execute("""
        UPDATE notifications
        SET message = '通知があります'
        WHERE message IS NULL OR message = ''
    """)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('message', existing_type=sa.Text(), nullable=False)
        batch_op.create_check_constraint(
            'ck_notifications_type_project_required',
            """
            (
              (
                type IN (
                  'application_received',
                  'department_pending',
                  'hq_pending',
                  'approved',
                  'rejected',
                  'completed'
                )
                AND project_id IS NOT NULL
              )
              OR
              (
                type IN ('system', 'announcement')
                AND project_id IS NULL
              )
            )
            """,
        )
        batch_op.drop_column('body')
        batch_op.drop_column('title')

    with op.batch_alter_table('project_status_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('to_status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('action', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('acted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_index(batch_op.f('ix_project_status_logs_created_at'))
        batch_op.create_index(batch_op.f('ix_project_status_logs_acted_at'), ['acted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_status_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_status_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_status_logs_to_status'), ['to_status'], unique=False)

    op.execute("""
        UPDATE project_status_logs
        SET from_status = old_status,
            to_status = new_status
        WHERE to_status IS NULL
    """)
    op.execute("""
        UPDATE project_status_logs
        SET to_status = 'department_pending'
        WHERE to_status IS NULL
    """)
    op.execute("""
        UPDATE project_status_logs
        SET action =
            CASE
                WHEN action_type IN ('submit', 'approve_department', 'approve_hq', 'reject_department', 'reject_hq', 'complete')
                    THEN action_type
                WHEN action_type = 'department_approve'
                    THEN 'approve_department'
                WHEN action_type = 'hq_approve'
                    THEN 'approve_hq'
                WHEN action_type = 'department_reject'
                    THEN 'reject_department'
                WHEN action_type = 'hq_reject'
                    THEN 'reject_hq'
                ELSE 'submit'
            END
        WHERE action IS NULL
    """)
    op.execute("""
        UPDATE project_status_logs
        SET comment = note
        WHERE comment IS NULL
    """)
    op.execute("""
        UPDATE project_status_logs
        SET acted_at = created_at
        WHERE acted_at IS NULL
    """)
    op.execute("""
        UPDATE project_status_logs
        SET acted_at = now()
        WHERE acted_at IS NULL
    """)

    with op.batch_alter_table('project_status_logs', schema=None) as batch_op:
        batch_op.alter_column('to_status', existing_type=sa.String(length=30), nullable=False)
        batch_op.alter_column('action', existing_type=sa.String(length=30), nullable=False)
        batch_op.alter_column('acted_at', existing_type=sa.DateTime(timezone=True), nullable=False)
        batch_op.create_check_constraint(
            'ck_project_status_logs_action_allowed',
            "action IN ('submit', 'approve_department', 'approve_hq', 'reject_department', 'reject_hq', 'complete')",
        )
        batch_op.create_check_constraint(
            'ck_project_status_logs_from_status_allowed',
            "from_status IS NULL OR from_status IN ('department_pending', 'hq_pending', 'in_progress', 'completed', 'rejected')",
        )
        batch_op.create_check_constraint(
            'ck_project_status_logs_to_status_allowed',
            "to_status IN ('department_pending', 'hq_pending', 'in_progress', 'completed', 'rejected')",
        )
        batch_op.drop_column('old_status')
        batch_op.drop_column('created_at')
        batch_op.drop_column('new_status')
        batch_op.drop_column('action_type')
        batch_op.drop_column('note')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('estimated_person_months', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('planned_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('planned_end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('monthly_report_comment', sa.Text(), nullable=True))

    op.execute("""
        UPDATE projects
        SET project_code = 'REQ-' || EXTRACT(YEAR FROM created_at)::int || '-' || LPAD(id::text, 5, '0')
        WHERE project_code IS NULL
    """)
    op.execute("""
        UPDATE projects
        SET estimated_person_months = estimated_budget_hours
        WHERE estimated_person_months IS NULL
    """)
    op.execute("""
        UPDATE projects p
        SET monthly_report_comment = latest.monthly_report_comment
        FROM (
            SELECT DISTINCT ON (project_id)
                project_id,
                monthly_report_comment
            FROM tasks
            WHERE monthly_report_comment IS NOT NULL
              AND monthly_report_comment <> ''
            ORDER BY project_id, updated_at DESC, id DESC
        ) latest
        WHERE p.id = latest.project_id
          AND p.monthly_report_comment IS NULL
    """)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('project_code', existing_type=sa.String(length=20), nullable=False)
        batch_op.alter_column('estimated_person_months', existing_type=sa.Numeric(precision=12, scale=2), nullable=False)
        batch_op.create_check_constraint(
            'ck_projects_estimated_person_months_non_negative',
            'estimated_person_months >= 0',
        )
        batch_op.create_index(batch_op.f('ix_projects_project_code'), ['project_code'], unique=True)
        batch_op.drop_column('rejection_reason_tag')
        batch_op.drop_column('estimated_budget_hours')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('monthly_report_comment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_report_comment', sa.TEXT(), autoincrement=False, nullable=True))

    op.execute("""
        UPDATE tasks t
        SET monthly_report_comment = p.monthly_report_comment
        FROM projects p
        WHERE p.id = t.project_id
          AND (t.monthly_report_comment IS NULL OR t.monthly_report_comment = '')
          AND p.monthly_report_comment IS NOT NULL
          AND p.monthly_report_comment <> ''
    """)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_budget_hours', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rejection_reason_tag', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.drop_constraint('ck_projects_estimated_person_months_non_negative', type_='check')

    op.execute("""
        UPDATE projects
        SET estimated_budget_hours = estimated_person_months
        WHERE estimated_budget_hours IS NULL
    """)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('estimated_budget_hours', existing_type=sa.Numeric(precision=12, scale=2), nullable=False)
        batch_op.drop_index(batch_op.f('ix_projects_project_code'))
        batch_op.drop_column('monthly_report_comment')
        batch_op.drop_column('planned_end_date')
        batch_op.drop_column('planned_start_date')
        batch_op.drop_column('estimated_person_months')
        batch_op.drop_column('project_code')

    with op.batch_alter_table('project_status_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('action_type', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('new_status', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('old_status', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.drop_constraint('ck_project_status_logs_to_status_allowed', type_='check')
        batch_op.drop_constraint('ck_project_status_logs_from_status_allowed', type_='check')
        batch_op.drop_constraint('ck_project_status_logs_action_allowed', type_='check')

    op.execute("""
        UPDATE project_status_logs
        SET old_status = from_status,
            new_status = to_status,
            action_type = action,
            note = comment,
            created_at = acted_at
        WHERE new_status IS NULL OR action_type IS NULL OR created_at IS NULL
    """)
    op.execute("""
        UPDATE project_status_logs
        SET new_status = 'department_pending'
        WHERE new_status IS NULL
    """)
    op.execute("""
        UPDATE project_status_logs
        SET action_type = 'submit'
        WHERE action_type IS NULL
    """)
    op.execute("""
        UPDATE project_status_logs
        SET created_at = now()
        WHERE created_at IS NULL
    """)

    with op.batch_alter_table('project_status_logs', schema=None) as batch_op:
        batch_op.alter_column('action_type', existing_type=sa.String(length=30), nullable=False)
        batch_op.alter_column('new_status', existing_type=sa.String(length=30), nullable=False)
        batch_op.alter_column('created_at', existing_type=sa.DateTime(timezone=True), nullable=False)
        batch_op.drop_index(batch_op.f('ix_project_status_logs_to_status'))
        batch_op.drop_index(batch_op.f('ix_project_status_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_project_status_logs_action'))
        batch_op.drop_index(batch_op.f('ix_project_status_logs_acted_at'))
        batch_op.create_index(batch_op.f('ix_project_status_logs_created_at'), ['created_at'], unique=False)
        batch_op.drop_column('acted_at')
        batch_op.drop_column('comment')
        batch_op.drop_column('action')
        batch_op.drop_column('to_status')
        batch_op.drop_column('from_status')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint('ck_notifications_type_project_required', type_='check')
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.alter_column('project_id',
               existing_type=sa.BIGINT(),
               nullable=False)

    op.execute("""
        UPDATE notifications
        SET title = CASE
                WHEN message IS NULL OR message = '' THEN '通知'
                ELSE LEFT(message, 200)
            END,
            body = COALESCE(message, '')
        WHERE title IS NULL OR body IS NULL
    """)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('title', existing_type=sa.String(length=200), nullable=False)
        batch_op.alter_column('body', existing_type=sa.Text(), nullable=False)
        batch_op.drop_column('message')

    with op.batch_alter_table('project_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_drafts_user_id'))
        batch_op.drop_index(batch_op.f('ix_project_drafts_department_id'))
        batch_op.drop_index(batch_op.f('ix_project_drafts_created_at'))

    op.drop_table('project_drafts')
    # ### end Alembic commands ###
