"""add planned dates to project drafts

Revision ID: ae9655238863
Revises: 88311347dd34
Create Date: 2026-05-04 00:54:24.502104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae9655238863'
down_revision = '88311347dd34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_drafts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planned_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('planned_end_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_drafts', schema=None) as batch_op:
        batch_op.drop_column('planned_end_date')
        batch_op.drop_column('planned_start_date')

    # ### end Alembic commands ###
