"""Create initial tables

Revision ID: bc57f288a677
Revises: 
Create Date: 2026-04-18 20:36:53.041359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc57f288a677'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('login_id', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('applicant', 'manager', 'hq')", name='ck_users_role_allowed'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('estimated_budget_hours', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estimated_budget_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('approved_budget_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('applicant_id', sa.BigInteger(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approval_stage', sa.String(length=30), nullable=False),
    sa.Column('rejection_reason_tag', sa.String(length=30), nullable=True),
    sa.Column('rejection_comment', sa.Text(), nullable=True),
    sa.Column('final_rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("approval_stage IN ('department_pending', 'hq_pending', 'approved', 'rejected')", name='ck_projects_approval_stage_allowed'),
    sa.CheckConstraint("rejection_reason_tag IS NULL OR rejection_reason_tag IN ('内容不備', '予算不足', '優先度低', '情報不足', 'その他')", name='ck_projects_rejection_reason_tag_allowed'),
    sa.CheckConstraint("status IN ('department_pending', 'hq_pending', 'in_progress', 'completed', 'rejected')", name='ck_projects_status_allowed'),
    sa.CheckConstraint('approved_budget_amount IS NULL OR approved_budget_amount >= 0', name='ck_projects_approved_budget_amount_non_negative'),
    sa.CheckConstraint('estimated_budget_amount >= 0', name='ck_projects_estimated_budget_amount_non_negative'),
    sa.CheckConstraint('estimated_budget_hours >= 0', name='ck_projects_estimated_budget_hours_non_negative'),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_applicant_id'), ['applicant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_approval_stage'), ['approval_stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)

    op.create_table('budget_actual_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('recorded_on', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_budget_actual_logs_amount_non_negative'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budget_actual_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_actual_logs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_actual_logs_recorded_on'), ['recorded_on'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('project_status_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=False),
    sa.Column('old_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_status_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_status_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_status_logs_project_id'), ['project_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('assignee_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_rate', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('monthly_report_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('not_started', 'in_progress', 'done')", name='ck_tasks_status_allowed'),
    sa.CheckConstraint('progress_rate >= 0 AND progress_rate <= 100', name='ck_tasks_progress_rate_range'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_project_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_due_date'))

    op.drop_table('tasks')
    with op.batch_alter_table('project_status_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_status_logs_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_status_logs_created_at'))

    op.drop_table('project_status_logs')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_project_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))

    op.drop_table('notifications')
    with op.batch_alter_table('budget_actual_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_actual_logs_recorded_on'))
        batch_op.drop_index(batch_op.f('ix_budget_actual_logs_project_id'))

    op.drop_table('budget_actual_logs')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_index(batch_op.f('ix_projects_department_id'))
        batch_op.drop_index(batch_op.f('ix_projects_approval_stage'))
        batch_op.drop_index(batch_op.f('ix_projects_applicant_id'))

    op.drop_table('projects')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))

    op.drop_table('users')
    op.drop_table('departments')
    # ### end Alembic commands ###
