"""add monthly report updated at to projects

Revision ID: c7696b33bebe
Revises: 4f9f41f6e331
Create Date: 2026-05-09 22:58:48.996654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7696b33bebe'
down_revision = '4f9f41f6e331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_report_updated_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('monthly_report_updated_at')

    # ### end Alembic commands ###
