"""add department members and task assignee member

Revision ID: f833bd041280
Revises: c7696b33bebe
Create Date: 2026-06-19 22:50:28.782757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f833bd041280'
down_revision = 'c7696b33bebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_members',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('can_assign_task', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('department_memberships',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('role_label', sa.String(length=50), nullable=True),
    sa.Column('joined_on', sa.Date(), nullable=True),
    sa.Column('left_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['department_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'department_id', name='uq_department_memberships_member_department')
    )
    with op.batch_alter_table('department_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_department_memberships_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_department_memberships_member_id'), ['member_id'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignee_member_id', sa.BigInteger(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tasks_assignee_member_id'), ['assignee_member_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_tasks_assignee_member_id_department_members',
            'department_members',
            ['assignee_member_id'],
            ['id'],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_tasks_assignee_member_id_department_members',
            type_='foreignkey',
        )
        batch_op.drop_index(batch_op.f('ix_tasks_assignee_member_id'))
        batch_op.drop_column('assignee_member_id')

    with op.batch_alter_table('department_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_department_memberships_member_id'))
        batch_op.drop_index(batch_op.f('ix_department_memberships_department_id'))

    op.drop_table('department_memberships')
    op.drop_table('department_members')
    # ### end Alembic commands ###
